steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'WANDB_KEY=$$SECRET_KEY']
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'KEY=$WANDB_KEY',
         '-t',
         'gcr.io/linear-rig-337909/group5_proj_cpu_container', 
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/linear-rig-337909/group5_proj_cpu_container']
availableSecrets:
  secretManager:
  - versionName: projects/688801769388/secrets/YOUR_API_KEY:latest
    env: 'SECRET_KEY'