steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'YOUR_API_KEY=$$SECRET_KEY',
         '-t',
         'gcr.io/linear-rig-337909/testing', 
         '.']
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/linear-rig-337909/testing']
availableSecrets:
  secretManager:
  - versionName: projects/688801769388/secrets/YOUR_API_KEY/versions/1
    env: 'SECRET_KEY'
